### ISSUE TITLE
Error when using `this` inside the Decorator. TypeError: this is undefined

### ISSUE THREAD

**Issue by dgonzalezr** [jarrvis/stencil-click-outside#1]
Can be the case that `this` is not available inside the `ClickOutside` decorator or am I missed something 🤔?

I have somewhere in my component a private method:

```javascript
  private toggleFocus = (focus: boolean) => {
    this._isFocus = focus;
  };
```

and when trying to use the `ClickOutside` decorator I set:

```javascript
  @ClickOutside()
  setFocusOut() {
    this.toggleFocus(false);
  }
```

which ended up with the following error:
`Uncaught TypeError: Cannot read property 'toggleFocus' of undefined`

**Comment by jarrvis** [comment]
Hi @dgonzalezr ,
thanks for reporting! you're obviously right. Issue fixed with:
https://github.com/jarrvis/stencil-click-outside/commit/cfe41fbcdd9ef0ad5eb42fc68b69e3fcebfe42c2
can you please check with version 1.2.0?

**Comment by dgonzalezr** [comment]
Hi @jarrvis, sorry for the delayed response. Yes it is fixed now, all good 👍
Thanks for handling it so quick  😃
