### ISSUE TITLE
Stencil v2 Lifecycle

### ISSUE THREAD

**Issue by daragh-king-genesys** [jarrvis/stencil-click-outside#6]
I think instead of using `componentDidLoad` and `componentDidUnload` the decorator should now use `connectedCallback` and `disconnectedCallback`.

From my research this will be compatible back to Stencil 1.9.0.

If you think this is correct I will be happy to create a PR

**Comment by jarrvis** [comment]
@daragh-king-genesys yes, obviously you are right. I just needed 8 months to think about it... 
I moved away from stencil unfortunately and missed the notification here. 
Anyway I merged the PR of @constantine-v and just pushed new version
